# Versión utilizada
# La versión 3 es la más utilizada y la que se recomienda
version: '3'

# Configuración de los servidores que vamos a necesitar
services:
# mysql es el nombre que vamos a dar a este primer servidor
  # Será el nombre que tendremos que usar cuando nos refiramos a él
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
    networks:
      - wpsite
    volumes:
       - mysql_data:/var/lib/mysql/

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    networks:
      - wpsite
  
  # Wordpress
  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    ports:
      - 80:80
    restart: always
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wpsite

  # Apache
  apache:
    build: apache/
    ports:
      - 8000:80
    volumes:
      - proyecto:/var/www/html/

  # PHP
  php:
    build: php/
    ports:
      - 9000:9000
    volumes:
      - proyecto:/var/www/html/

networks:
  wpsite:

volumes:
  mysql_data:
  proyecto: